name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: YashKhandelwal0705
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
